repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Basics
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

      # Specific files
      - id: check-toml
      - id: check-json
      - id: check-yaml
      - id: check-xml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff-check
      - id: ruff-format
